### PR TITLE
Iff pdu improvements and Unsafe equalsImpl for object list attributes

### PR DESCRIPTION
**Pull request by mimmi-matalamaki-insta-fi**
We have generated code based on https://github.com/open-dis/opendis7-source-generator/pull/15 -pullrequest open in opendis7-source-generator project. We have added IFFPduTest.java and Mode5StatusRecord.java classes.

### CODE REVIEW

**Comment by brutzman** [comment]
We are first testing the opendis7-source-generator pull request first, in order to see if that handles these dependencies when updating via _build all_.

**Comment by brutzman** [comment]
We are committing and pushing the following files manually since all of the other changes were autogenerated files that are now superseded.
- edu.nps.moves.dis7.test.IFFPduTest.java 
- edu.nps.moves.dis7.utilities.Mode5StatusRecord

Wondering if the second class is better positioned next to IFFLayer3 and renamed as
-  edu.nps.moves.dis7.pdus.IFFMode5StatusRecord

Feedback welcome.  We plan to perform this refactoring if there are no objections.

**Comment by mimmi-matalamaki-insta-fi** [comment]
Hello, for us it is ofcourse okay that you refactor class names and the code the way you like it better.

**Comment by brutzman** [comment]
All merges handled manually, all conflicts resolved.

**Pull request closed without merging**
